name: Release

on:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:

  release:
    runs-on: ubuntu-latest

    env:
      ReferenceUrl: https://exmod-team.github.io/SL-References/Dev.zip
      ReferencePath: ${{ github.workspace }}/References

    steps:

      - uses: actions/checkout@v4

      - name: Set Up .NET
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 9.0.x

      - name: Download References
        run: |
          wget -O "References.zip" ${{ env.ReferenceUrl }}
          unzip -d ${{ env.ReferencePath }} "References.zip"

      - name: Rename Publicized Assemblies
        working-directory: ${{ env.ReferencePath }}
        run: |
          mv Assembly-CSharp-Publicized.dll Assembly-CSharp.dll
          mv Mirror-Publicized.dll Mirror.dll

      - name: Build
        run: dotnet build -c Release -o Output

      - name: Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: "Output/Axwabo.Helpers.dll,Output/Axwabo.Helpers.xml"
